
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class CalificacionColaborador
{

    public long nCalificacionColaboradorId { get; set; }

    public string sComentario { get; set; }

    public int nPuntuacion { get; set; }

    public long nFuncionarioId { get; set; }

    public long nClienteId { get; set; }

    public long nEventoId { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }

    public int nCalificado { get; set; }



    public virtual Evento Evento { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
