

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class dbFexpoCruzEntities : DbContext
{
    public dbFexpoCruzEntities()
        : base("name=dbFexpoCruzEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Bitacora> Bitacora { get; set; }

    public virtual DbSet<Permiso> Permiso { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    public virtual DbSet<Ciudad> Ciudad { get; set; }

    public virtual DbSet<Pais> Pais { get; set; }

    public virtual DbSet<Empresa> Empresa { get; set; }

    public virtual DbSet<TipoAtencion> TipoAtencion { get; set; }

    public virtual DbSet<Dia> Dia { get; set; }

    public virtual DbSet<HorarioColaborador> HorarioColaborador { get; set; }

    public virtual DbSet<Area> Area { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<EstadoEvento> EstadoEvento { get; set; }

    public virtual DbSet<HistorialEstadoEvento> HistorialEstadoEvento { get; set; }

    public virtual DbSet<Evento> Evento { get; set; }

    public virtual DbSet<EventoHilo> EventoHilo { get; set; }

    public virtual DbSet<Mensaje> Mensaje { get; set; }

    public virtual DbSet<NotificacionFuncionario> NotificacionFuncionario { get; set; }

    public virtual DbSet<Hilo> Hilo { get; set; }

    public virtual DbSet<PreguntaFrecuente> PreguntaFrecuente { get; set; }

    public virtual DbSet<CategoriaPreguntaFrecuente> CategoriaPreguntaFrecuente { get; set; }

    public virtual DbSet<Funcionario> Funcionario { get; set; }

    public virtual DbSet<CalificacionColaborador> CalificacionColaborador { get; set; }


    public virtual ObjectResult<getComisionesServicios_Result> getComisionesServicios(string fechaInicio, string fechaFin)
    {

        var fechaInicioParameter = fechaInicio != null ?
            new ObjectParameter("fechaInicio", fechaInicio) :
            new ObjectParameter("fechaInicio", typeof(string));


        var fechaFinParameter = fechaFin != null ?
            new ObjectParameter("fechaFin", fechaFin) :
            new ObjectParameter("fechaFin", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComisionesServicios_Result>("getComisionesServicios", fechaInicioParameter, fechaFinParameter);
    }


    public virtual ObjectResult<getComisionesServicios1_Result> getComisionesServicios1()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComisionesServicios1_Result>("getComisionesServicios1");
    }


    public virtual ObjectResult<getComisionesProductos_Result> getComisionesProductos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComisionesProductos_Result>("getComisionesProductos");
    }


    public virtual ObjectResult<getDeudasCobrosProducto_Result> getDeudasCobrosProducto()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDeudasCobrosProducto_Result>("getDeudasCobrosProducto");
    }


    public virtual ObjectResult<getDeudasCobrosServicio_Result> getDeudasCobrosServicio()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getDeudasCobrosServicio_Result>("getDeudasCobrosServicio");
    }


    public virtual ObjectResult<getVentaProducto_Result> getVentaProducto()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getVentaProducto_Result>("getVentaProducto");
    }


    public virtual ObjectResult<getVentaServicio_Result> getVentaServicio()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getVentaServicio_Result>("getVentaServicio");
    }


    public virtual ObjectResult<getServicioMasVendidos_Result> getServicioMasVendidos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getServicioMasVendidos_Result>("getServicioMasVendidos");
    }


    public virtual ObjectResult<getProductoMasVendidos_Result> getProductoMasVendidos()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductoMasVendidos_Result>("getProductoMasVendidos");
    }


    public virtual ObjectResult<getRendimientoProfesional_Result> getRendimientoProfesional()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRendimientoProfesional_Result>("getRendimientoProfesional");
    }


    public virtual ObjectResult<getPermisoSolicitud_Result> getPermisoSolicitud()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getPermisoSolicitud_Result>("getPermisoSolicitud");
    }

}

}

