
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Evento
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Evento()
    {

        this.EventoHilo = new HashSet<EventoHilo>();

        this.HistorialEstadoEvento = new HashSet<HistorialEstadoEvento>();

        this.CalificacionColaborador = new HashSet<CalificacionColaborador>();

    }


    public long nEventoId { get; set; }

    public long nEstadoEventoId { get; set; }

    public long nClienteId { get; set; }

    public long nTipoAtencionId { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual EstadoEvento EstadoEvento { get; set; }

    public virtual TipoAtencion TipoAtencion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EventoHilo> EventoHilo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HistorialEstadoEvento> HistorialEstadoEvento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalificacionColaborador> CalificacionColaborador { get; set; }

}

}
