
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Funcionario
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Funcionario()
    {

        this.Hilo = new HashSet<Hilo>();

        this.HorarioColaborador = new HashSet<HorarioColaborador>();

        this.Mensaje = new HashSet<Mensaje>();

        this.NotificacionFuncionario = new HashSet<NotificacionFuncionario>();

        this.CalificacionColaborador = new HashSet<CalificacionColaborador>();

    }


    public long nFuncionarioId { get; set; }

    public string sNombre { get; set; }

    public string sApellido { get; set; }

    public string sCi { get; set; }

    public Nullable<int> nEstado { get; set; }

    public int nSexo { get; set; }

    public long nUsuarioCreador { get; set; }

    public long nUsuarioModificador { get; set; }

    public System.DateTime dtFechaCreacion { get; set; }

    public System.DateTime dtFechaModificacion { get; set; }

    public string sFotoPefil { get; set; }

    public Nullable<int> nTipo { get; set; }

    public Nullable<long> nAreaId { get; set; }

    public Nullable<long> nCiudadId { get; set; }

    public Nullable<decimal> nPuntaje { get; set; }



    public virtual Area Area { get; set; }

    public virtual Ciudad Ciudad { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Hilo> Hilo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<HorarioColaborador> HorarioColaborador { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Mensaje> Mensaje { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NotificacionFuncionario> NotificacionFuncionario { get; set; }

    public virtual Usuario Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CalificacionColaborador> CalificacionColaborador { get; set; }

}

}
