
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Hilo
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hilo()
    {

        this.EventoHilo = new HashSet<EventoHilo>();

    }


    public long nHiloId { get; set; }

    public string sCodigo { get; set; }

    public Nullable<long> nFuncionarioId { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }

    public int nEstado { get; set; }

    public int nActual { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EventoHilo> EventoHilo { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
