
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class HistorialEstadoEvento
{

    public long nHistorialEstadoEventoId { get; set; }

    public long nEstadoEventoId { get; set; }

    public long nEventoId { get; set; }

    public string sDescripcion { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }



    public virtual EstadoEvento EstadoEvento { get; set; }

    public virtual Evento Evento { get; set; }

}

}
