
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Mensaje
{

    public long nMensajeId { get; set; }

    public string sTexto { get; set; }

    public string sArchivo { get; set; }

    public int nEstado { get; set; }

    public long nEventoHiloId { get; set; }

    public Nullable<long> nClienteId { get; set; }

    public Nullable<long> nFuncionarioId { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }



    public virtual Cliente Cliente { get; set; }

    public virtual EventoHilo EventoHilo { get; set; }

    public virtual Funcionario Funcionario { get; set; }

}

}
