
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class PreguntaFrecuente
{

    public long nPreguntaFrecuenteId { get; set; }

    public string sPregunta { get; set; }

    public int nEstado { get; set; }

    public long nTipoAtencionId { get; set; }

    public long nCategoriaPreguntaFrecuenteId { get; set; }

    public System.DateTime dFechaCreacion { get; set; }

    public System.DateTime dFechaModificacion { get; set; }



    public virtual TipoAtencion TipoAtencion { get; set; }

    public virtual CategoriaPreguntaFrecuente CategoriaPreguntaFrecuente { get; set; }

}

}
