//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public long BitacoraId { get; set; }
        public string Accion { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<long> UsuarioId { get; set; }
        public string Transaccion { get; set; }
        public string Detalle { get; set; }
        public int Tipo { get; set; }
        public Nullable<long> IdImplicado { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
