//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFexpoCruzEntities : DbContext
    {
        public dbFexpoCruzEntities()
            : base("name=dbFexpoCruzEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<CalificacionColaborador> CalificacionColaborador { get; set; }
        public virtual DbSet<CategoriaPreguntaFrecuente> CategoriaPreguntaFrecuente { get; set; }
        public virtual DbSet<Ciudad> Ciudad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Dia> Dia { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<EstadoEvento> EstadoEvento { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<EventoHilo> EventoHilo { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Hilo> Hilo { get; set; }
        public virtual DbSet<HistorialEstadoEvento> HistorialEstadoEvento { get; set; }
        public virtual DbSet<HorarioColaborador> HorarioColaborador { get; set; }
        public virtual DbSet<Mensaje> Mensaje { get; set; }
        public virtual DbSet<NotificacionFuncionario> NotificacionFuncionario { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<PreguntaFrecuente> PreguntaFrecuente { get; set; }
        public virtual DbSet<TipoAtencion> TipoAtencion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
